config/routes.rb
Rails.application.routes.draw do



  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'sessions/new'

  resources :users

  resources :account_activations, only: [:edit]

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/login'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Login</a>
    by <a href="https://www.facebook.com/EseJesAliasElYisus">Yisus Ruedas</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
      <li><a href="http://ruby.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "UTFV app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio", root_path %></li>
        <li><%= link_to "Ayuda", static_pages_help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Salir", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Iniciar Sesion", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UTFV</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>